In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [9]:
dataset= pd.read_csv('weather.csv')
X=dataset.iloc[:, 1:5].values 
y=dataset.iloc[:,0].values

In [10]:
y

array([-0.55555556, 21.11111111, 16.6       , ...,  5.97777778,
        9.78888889, 11.13888889])

In [11]:
X

array([[  0.92  ,  11.27  , 130.    ,   8.05  ],
       [  0.73  ,  20.93  , 330.    ,  16.1   ],
       [  0.97  ,   5.9731, 193.    ,  14.9086],
       ...,
       [  0.93  ,  11.0446, 269.    ,  14.9086],
       [  0.78  ,   8.1788, 231.    ,   7.8246],
       [  0.79  ,  14.2485, 131.    ,  10.2557]])

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test= train_test_split(X,y,test_size=1/3,random_state=0)

In [13]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [16]:
y_pred =  regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))  

[[18.32 21.18]
 [ 5.92  6.26]
 [ 9.94  2.64]
 ...
 [11.66 21.21]
 [16.63 -5.93]
 [13.42  2.84]]
